# BACKPROPAGATION NEURAL NETWORK

In [ ]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
print(X)
print(y)
X = X/np.amax(X, axis=0) 
y = y/100 
print(X)
print(y)
class Neural_Network(object):
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) 
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)
    def forward(self, X):
        self.z = np.dot(X, self.W1) 
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2) 
        o = self.sigmoid(self.z3) 
        return o 
    def sigmoid(self, s):
        return 1/(1+np.exp(-s))
    def sigmoidPrime(self, s):
        return s * (1 - s)
    def backward(self, X, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error*self.sigmoidPrime(o) 
        self.z2_error = self.o_delta.dot(self.W2.T) 
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
        self.W1 += X.T.dot(self.z2_delta) 
        self.W2 += self.z2.T.dot(self.o_delta)
    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)
NN = Neural_Network()
for i in range(1000): 
        print ("Input: \n" + str(X)) 
        print ("Actual Output: \n" + str(y)) 
        print ("Predicted Output: \n" + str(NN.forward(X))) 
        print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) 
        print ("\n")
        NN.train(X, y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.25108337]
 [0.24808705]
 [0.28632093]]
Loss: 
0.3954384456323016


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.31896131]
 [0.31050939]
 [0.35801615]]
Loss: 
0.31539808198911373


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.3920412 ]
 [0.37842756]
 [0.43303855]]
Loss: 
0.2398220927436985


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.46307979]
 [0.44523785]
 [0.50424829]]
Loss: 
0.1765360

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89660154]
 [0.86641373]
 [0.90791752]]
Loss: 
0.0003032204370702834


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89660821]
 [0.86641412]
 [0.90790679]]
Loss: 
0.0003029900200339751


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89661487]
 [0.8664145 ]
 [0.90789607]]
Loss: 
0.00030275983255436545


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89662152]
 [0.86641488]
 [0.90788534]]
Loss: 
0.00030252987440126873


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
P

Predicted Output: 
[[0.89803135]
 [0.86651606]
 [0.90558766]]
Loss: 
0.000256018681650662


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89803727]
 [0.86651664]
 [0.90557811]]
Loss: 
0.00025583526395192655


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89804318]
 [0.86651722]
 [0.90556856]]
Loss: 
0.00025565202869192604


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8980491 ]
 [0.8665178 ]
 [0.90555902]]
Loss: 
0.00025546897568674566


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89805501]
 [0.86651838]
 [0.90554949]]
Loss: 
0.0002552861047526508


Input: 
[[0.66666667 1.        ]


 [0.89]]
Predicted Output: 
[[0.89950842]
 [0.86669641]
 [0.90324645]]
Loss: 
0.00021340495602344223


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8995137 ]
 [0.86669716]
 [0.90323824]]
Loss: 
0.0002132638100115804


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89951898]
 [0.86669792]
 [0.90323005]]
Loss: 
0.00021312280339487043


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89952426]
 [0.86669868]
 [0.90322186]]
Loss: 
0.0002129819360293987


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89952953]
 [0.86669943]
 [0.90321367]]
Loss: 
0.00021284120777138055


Input: 
[[0.66666667 1.